# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/asr_dlhlp_ctc_sd0/best_ctc.pth'
  config: 'config/libri/asr_dlhlp_ctc.yaml'
data:
  corpus:
    name:  'Dlhlp'
    dev_split: ['dev']
    test_split: ['test']
decode:
  beam_size: 5
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path:
  lm_config:
  lm_weight: 0.0
  ctc_weight: 0.5

hparas:
  optimizer: 'Adadelta'

